import {
  Baby,
  Bath,
  BedDouble,
  CarFront,
  Clock3,
  Coffee,
  CreditCard,
  Flame,
  MapPin,
  Mountain,
  Phone,
  ShieldCheck,
  ShowerHead,
  Snowflake,
  Sparkles,
  Star,
  Ticket,
  Trees,
  Tv,
  UsersRound,
  UtensilsCrossed,
  Waves,
  Accessibility,
  Wifi,
  AirVent,
  Armchair,
  ArrowUpDown,
  Award,
  BadgeCheck,
  Ban,
  BatteryCharging,
  Bell,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Bus,
  Camera,
  Castle,
  ChefHat,
  Check,
  CircleHelp,
  Clapperboard,
  CloudSun,
  Compass,
  ConciergeBell,
  CookingPot,
  DoorOpen,
  Dumbbell,
  Fan,
  Fence,
  Flower2,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  Globe2,
  Handshake,
  Heart,
  HeartPulse,
  Heater,
  House,
  IceCreamCone,
  KeyRound,
  LampDesk,
  Laptop,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Luggage,
  Mail,
  Map,
  Martini,
  Microwave,
  Music2,
  Navigation,
  Package,
  PawPrint,
  Plane,
  Plug,
  Refrigerator,
  Sailboat,
  Search,
  Ship,
  ShoppingBag,
  Smartphone,
  Sofa,
  Soup,
  Speaker,
  Sun,
  Thermometer,
  Train,
  Trash2,
  Truck,
  Umbrella,
  Video,
  WashingMachine,
  Wind,
  Wine,
  Zap,
  type LucideIcon,
} from "lucide-react";
import {
  Activity,
  AlarmClock,
  Anchor,
  Backpack,
  BadgePercent,
  BedSingle,
  Beer,
  BellRing,
  Binoculars,
  Cake,
  CalendarDays,
  CalendarCheck,
  Car,
  CarTaxiFront,
  CheckCircle2,
  CircleParking,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  CloudRain,
  Coins,
  Croissant,
  CupSoda,
  DoorClosed,
  Droplets,
  Fish,
  Flag,
  Flashlight,
  Fuel,
  GalleryHorizontal,
  HandHeart,
  HandPlatter,
  Headphones,
  HeartHandshake,
  Hotel,
  Hourglass,
  Image,
  Info,
  KeySquare,
  LampCeiling,
  LampFloor,
  Languages,
  Library,
  LifeBuoy,
  Lock,
  MapPinned,
  Medal,
  Megaphone,
  Moon,
  PackageCheck,
  Palmtree,
  PartyPopper,
  PenLine,
  Percent,
  PersonStanding,
  PiggyBank,
  Pizza,
  Popcorn,
  Presentation,
  Printer,
  Projector,
  Radio,
  Receipt,
  Recycle,
  RefreshCcw,
  Rocket,
  Route,
  Salad,
  ScanFace,
  Scissors,
  ScrollText,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Signal,
  Siren,
  SlidersHorizontal,
  Smile,
  Sprout,
  SquareCheck,
  Stethoscope,
  Store,
  Sunset,
  Table,
  Tag,
  Telescope,
  Tent,
  Theater,
  ThumbsUp,
  Timer,
  Toilet,
  TrainFront,
  TramFront,
  TreePine,
  Trophy,
  UserCheck,
  Wallet,
  Warehouse,
  Wrench,
} from "lucide-react";

export const masterIcons: {
  key: string;
  nameId: string;
  nameEn: string;
  Icon: LucideIcon;
}[] = [
  { key: "bed", nameId: "Tempat tidur", nameEn: "Bed", Icon: BedDouble },
  { key: "wifi", nameId: "Wi-Fi", nameEn: "Wi-Fi", Icon: Wifi },
  { key: "parking", nameId: "Parkir", nameEn: "Parking", Icon: CarFront },
  {
    key: "utensils",
    nameId: "Restoran",
    nameEn: "Dining",
    Icon: UtensilsCrossed,
  },
  { key: "coffee", nameId: "Kopi", nameEn: "Coffee", Icon: Coffee },
  { key: "waves", nameId: "Kolam renang", nameEn: "Pool", Icon: Waves },
  { key: "sparkles", nameId: "Spa", nameEn: "Spa", Icon: Sparkles },
  { key: "tv", nameId: "Televisi", nameEn: "TV", Icon: Tv },
  {
    key: "snowflake",
    nameId: "AC",
    nameEn: "Air conditioning",
    Icon: Snowflake,
  },
  { key: "mountain", nameId: "Gunung", nameEn: "Mountain", Icon: Mountain },
  { key: "trees", nameId: "Taman", nameEn: "Garden", Icon: Trees },
  { key: "bath", nameId: "Bathtub", nameEn: "Bathtub", Icon: Bath },
  { key: "shower-head", nameId: "Shower", nameEn: "Shower", Icon: ShowerHead },
  { key: "flame", nameId: "Air panas", nameEn: "Hot water", Icon: Flame },
  {
    key: "shield-check",
    nameId: "Keamanan",
    nameEn: "Safety",
    Icon: ShieldCheck,
  },
  { key: "users", nameId: "Tamu", nameEn: "Guests", Icon: UsersRound },
  { key: "baby", nameId: "Anak", nameEn: "Children", Icon: Baby },
  {
    key: "accessibility",
    nameId: "Aksesibilitas",
    nameEn: "Accessibility",
    Icon: Accessibility,
  },
  { key: "map-pin", nameId: "Lokasi", nameEn: "Location", Icon: MapPin },
  {
    key: "credit-card",
    nameId: "Pembayaran",
    nameEn: "Payment",
    Icon: CreditCard,
  },
  { key: "ticket", nameId: "Pengalaman", nameEn: "Experience", Icon: Ticket },
  { key: "phone", nameId: "Telepon", nameEn: "Phone", Icon: Phone },
  { key: "clock", nameId: "Waktu", nameEn: "Time", Icon: Clock3 },
  { key: "star", nameId: "Bintang", nameEn: "Star", Icon: Star },
  {
    key: "air-vent",
    nameId: "Ventilasi",
    nameEn: "Ventilation",
    Icon: AirVent,
  },
  { key: "armchair", nameId: "Kursi", nameEn: "Armchair", Icon: Armchair },
  {
    key: "arrow-up-down",
    nameId: "Lift",
    nameEn: "Elevator",
    Icon: ArrowUpDown,
  },
  { key: "award", nameId: "Penghargaan", nameEn: "Award", Icon: Award },
  {
    key: "badge-check",
    nameId: "Terverifikasi",
    nameEn: "Verified",
    Icon: BadgeCheck,
  },
  { key: "ban", nameId: "Dilarang", nameEn: "Not allowed", Icon: Ban },
  {
    key: "battery-charging",
    nameId: "Pengisian daya",
    nameEn: "Charging",
    Icon: BatteryCharging,
  },
  { key: "bell", nameId: "Bel", nameEn: "Bell", Icon: Bell },
  { key: "bike", nameId: "Sepeda", nameEn: "Bicycle", Icon: Bike },
  { key: "book-open", nameId: "Buku", nameEn: "Book", Icon: BookOpen },
  {
    key: "briefcase-business",
    nameId: "Bisnis",
    nameEn: "Business",
    Icon: BriefcaseBusiness,
  },
  { key: "building2", nameId: "Gedung", nameEn: "Building", Icon: Building2 },
  { key: "bus", nameId: "Bus", nameEn: "Bus", Icon: Bus },
  { key: "camera", nameId: "Kamera", nameEn: "Camera", Icon: Camera },
  { key: "castle", nameId: "Kastel", nameEn: "Castle", Icon: Castle },
  { key: "chef-hat", nameId: "Koki", nameEn: "Chef", Icon: ChefHat },
  { key: "check", nameId: "Centang", nameEn: "Check", Icon: Check },
  { key: "circle-help", nameId: "Bantuan", nameEn: "Help", Icon: CircleHelp },
  {
    key: "clapperboard",
    nameId: "Hiburan",
    nameEn: "Entertainment",
    Icon: Clapperboard,
  },
  { key: "cloud-sun", nameId: "Cuaca", nameEn: "Weather", Icon: CloudSun },
  { key: "compass", nameId: "Kompas", nameEn: "Compass", Icon: Compass },
  {
    key: "concierge-bell",
    nameId: "Layanan kamar",
    nameEn: "Room service",
    Icon: ConciergeBell,
  },
  { key: "cooking-pot", nameId: "Dapur", nameEn: "Kitchen", Icon: CookingPot },
  { key: "door-open", nameId: "Pintu", nameEn: "Entrance", Icon: DoorOpen },
  { key: "dumbbell", nameId: "Gym", nameEn: "Gym", Icon: Dumbbell },
  { key: "fan", nameId: "Kipas", nameEn: "Fan", Icon: Fan },
  { key: "fence", nameId: "Pagar", nameEn: "Fence", Icon: Fence },
  { key: "flower2", nameId: "Bunga", nameEn: "Flower", Icon: Flower2 },
  {
    key: "footprints",
    nameId: "Jalur jalan",
    nameEn: "Walking path",
    Icon: Footprints,
  },
  { key: "gamepad2", nameId: "Permainan", nameEn: "Games", Icon: Gamepad2 },
  { key: "gift", nameId: "Hadiah", nameEn: "Gift", Icon: Gift },
  {
    key: "glass-water",
    nameId: "Air minum",
    nameEn: "Drinking water",
    Icon: GlassWater,
  },
  { key: "globe2", nameId: "Global", nameEn: "Global", Icon: Globe2 },
  {
    key: "handshake",
    nameId: "Kerja sama",
    nameEn: "Partnership",
    Icon: Handshake,
  },
  { key: "heart", nameId: "Favorit", nameEn: "Favorite", Icon: Heart },
  {
    key: "heart-pulse",
    nameId: "Kesehatan",
    nameEn: "Health",
    Icon: HeartPulse,
  },
  { key: "heater", nameId: "Pemanas", nameEn: "Heater", Icon: Heater },
  { key: "house", nameId: "Rumah", nameEn: "House", Icon: House },
  {
    key: "ice-cream-cone",
    nameId: "Es krim",
    nameEn: "Ice cream",
    Icon: IceCreamCone,
  },
  { key: "key-round", nameId: "Kunci", nameEn: "Key", Icon: KeyRound },
  {
    key: "lamp-desk",
    nameId: "Lampu meja",
    nameEn: "Desk lamp",
    Icon: LampDesk,
  },
  { key: "laptop", nameId: "Laptop", nameEn: "Laptop", Icon: Laptop },
  { key: "leaf", nameId: "Alam", nameEn: "Nature", Icon: Leaf },
  { key: "lightbulb", nameId: "Lampu", nameEn: "Light", Icon: Lightbulb },
  {
    key: "lock-keyhole",
    nameId: "Kunci aman",
    nameEn: "Secure lock",
    Icon: LockKeyhole,
  },
  { key: "luggage", nameId: "Bagasi", nameEn: "Luggage", Icon: Luggage },
  { key: "mail", nameId: "Email", nameEn: "Email", Icon: Mail },
  { key: "map", nameId: "Peta", nameEn: "Map", Icon: Map },
  { key: "martini", nameId: "Bar", nameEn: "Bar", Icon: Martini },
  {
    key: "microwave",
    nameId: "Microwave",
    nameEn: "Microwave",
    Icon: Microwave,
  },
  { key: "music2", nameId: "Musik", nameEn: "Music", Icon: Music2 },
  {
    key: "navigation",
    nameId: "Navigasi",
    nameEn: "Navigation",
    Icon: Navigation,
  },
  { key: "package", nameId: "Paket", nameEn: "Package", Icon: Package },
  {
    key: "paw-print",
    nameId: "Hewan peliharaan",
    nameEn: "Pets",
    Icon: PawPrint,
  },
  { key: "plane", nameId: "Pesawat", nameEn: "Plane", Icon: Plane },
  { key: "plug", nameId: "Stopkontak", nameEn: "Power outlet", Icon: Plug },
  {
    key: "refrigerator",
    nameId: "Kulkas",
    nameEn: "Refrigerator",
    Icon: Refrigerator,
  },
  { key: "sailboat", nameId: "Perahu", nameEn: "Sailboat", Icon: Sailboat },
  { key: "search", nameId: "Cari", nameEn: "Search", Icon: Search },
  { key: "ship", nameId: "Kapal", nameEn: "Ship", Icon: Ship },
  {
    key: "shopping-bag",
    nameId: "Belanja",
    nameEn: "Shopping",
    Icon: ShoppingBag,
  },
  {
    key: "smartphone",
    nameId: "Ponsel",
    nameEn: "Smartphone",
    Icon: Smartphone,
  },
  { key: "sofa", nameId: "Sofa", nameEn: "Sofa", Icon: Sofa },
  { key: "soup", nameId: "Sup", nameEn: "Soup", Icon: Soup },
  {
    key: "speaker",
    nameId: "Pengeras suara",
    nameEn: "Speaker",
    Icon: Speaker,
  },
  { key: "sun", nameId: "Matahari", nameEn: "Sun", Icon: Sun },
  {
    key: "thermometer",
    nameId: "Suhu",
    nameEn: "Temperature",
    Icon: Thermometer,
  },
  { key: "train", nameId: "Kereta", nameEn: "Train", Icon: Train },
  { key: "trash2", nameId: "Tempat sampah", nameEn: "Trash", Icon: Trash2 },
  { key: "truck", nameId: "Truk", nameEn: "Truck", Icon: Truck },
  { key: "umbrella", nameId: "Payung", nameEn: "Umbrella", Icon: Umbrella },
  { key: "video", nameId: "Video", nameEn: "Video", Icon: Video },
  {
    key: "washing-machine",
    nameId: "Mesin cuci",
    nameEn: "Washing machine",
    Icon: WashingMachine,
  },
  { key: "wind", nameId: "Angin", nameEn: "Wind", Icon: Wind },
  { key: "wine", nameId: "Anggur", nameEn: "Wine", Icon: Wine },
  { key: "zap", nameId: "Listrik", nameEn: "Electricity", Icon: Zap },
  { key: "activity", nameId: "Aktivitas", nameEn: "Activity", Icon: Activity },
  {
    key: "alarm-clock",
    nameId: "Alarm",
    nameEn: "Alarm Clock",
    Icon: AlarmClock,
  },
  { key: "anchor", nameId: "Jangkar", nameEn: "Anchor", Icon: Anchor },
  { key: "backpack", nameId: "Ransel", nameEn: "Backpack", Icon: Backpack },
  {
    key: "badge-percent",
    nameId: "Diskon",
    nameEn: "Discount",
    Icon: BadgePercent,
  },
  {
    key: "bed-single",
    nameId: "Kasur single",
    nameEn: "Single bed",
    Icon: BedSingle,
  },
  { key: "beer", nameId: "Bir", nameEn: "Beer", Icon: Beer },
  {
    key: "bell-ring",
    nameId: "Bel berdering",
    nameEn: "Ringing bell",
    Icon: BellRing,
  },
  {
    key: "binoculars",
    nameId: "Teropong",
    nameEn: "Binoculars",
    Icon: Binoculars,
  },
  { key: "cake", nameId: "Kue", nameEn: "Cake", Icon: Cake },
  {
    key: "calendar-days",
    nameId: "Kalender",
    nameEn: "Calendar Days",
    Icon: CalendarDays,
  },
  {
    key: "calendar-check",
    nameId: "Jadwal terkonfirmasi",
    nameEn: "Confirmed schedule",
    Icon: CalendarCheck,
  },
  { key: "car", nameId: "Mobil", nameEn: "Car", Icon: Car },
  {
    key: "car-taxi-front",
    nameId: "Taksi",
    nameEn: "Taxi",
    Icon: CarTaxiFront,
  },
  {
    key: "check-circle2",
    nameId: "Selesai",
    nameEn: "Completed",
    Icon: CheckCircle2,
  },
  {
    key: "circle-parking",
    nameId: "Area parkir",
    nameEn: "Parking area",
    Icon: CircleParking,
  },
  {
    key: "clipboard-check",
    nameId: "Daftar periksa",
    nameEn: "Checklist",
    Icon: ClipboardCheck,
  },
  {
    key: "clipboard-list",
    nameId: "Daftar",
    nameEn: "List",
    Icon: ClipboardList,
  },
  { key: "cloud", nameId: "Awan", nameEn: "Cloud", Icon: Cloud },
  { key: "cloud-rain", nameId: "Hujan", nameEn: "Cloud Rain", Icon: CloudRain },
  { key: "coins", nameId: "Koin", nameEn: "Coins", Icon: Coins },
  { key: "croissant", nameId: "Roti", nameEn: "Croissant", Icon: Croissant },
  { key: "cup-soda", nameId: "Minuman", nameEn: "Drink", Icon: CupSoda },
  {
    key: "door-closed",
    nameId: "Pintu tertutup",
    nameEn: "Door Closed",
    Icon: DoorClosed,
  },
  { key: "droplets", nameId: "Air", nameEn: "Droplets", Icon: Droplets },
  { key: "fish", nameId: "Ikan", nameEn: "Fish", Icon: Fish },
  { key: "flag", nameId: "Bendera", nameEn: "Flag", Icon: Flag },
  {
    key: "flashlight",
    nameId: "Senter",
    nameEn: "Flashlight",
    Icon: Flashlight,
  },
  { key: "fuel", nameId: "Bahan bakar", nameEn: "Fuel", Icon: Fuel },
  {
    key: "gallery-horizontal",
    nameId: "Galeri",
    nameEn: "Gallery",
    Icon: GalleryHorizontal,
  },
  { key: "hand-heart", nameId: "Kepedulian", nameEn: "Care", Icon: HandHeart },
  {
    key: "hand-platter",
    nameId: "Pelayanan",
    nameEn: "Service",
    Icon: HandPlatter,
  },
  {
    key: "headphones",
    nameId: "Headphone",
    nameEn: "Headphones",
    Icon: Headphones,
  },
  {
    key: "heart-handshake",
    nameId: "Layanan ramah",
    nameEn: "Friendly service",
    Icon: HeartHandshake,
  },
  { key: "hotel", nameId: "Hotel", nameEn: "Hotel", Icon: Hotel },
  {
    key: "hourglass",
    nameId: "Jam pasir",
    nameEn: "Hourglass",
    Icon: Hourglass,
  },
  { key: "image", nameId: "Gambar", nameEn: "Image", Icon: Image },
  { key: "info", nameId: "Informasi", nameEn: "Info", Icon: Info },
  {
    key: "key-square",
    nameId: "Kunci kamar",
    nameEn: "Room key",
    Icon: KeySquare,
  },
  {
    key: "lamp-ceiling",
    nameId: "Lampu plafon",
    nameEn: "Lamp Ceiling",
    Icon: LampCeiling,
  },
  {
    key: "lamp-floor",
    nameId: "Lampu lantai",
    nameEn: "Lamp Floor",
    Icon: LampFloor,
  },
  { key: "languages", nameId: "Bahasa", nameEn: "Languages", Icon: Languages },
  { key: "library", nameId: "Perpustakaan", nameEn: "Library", Icon: Library },
  {
    key: "life-buoy",
    nameId: "Pelampung",
    nameEn: "Life Buoy",
    Icon: LifeBuoy,
  },
  { key: "lock", nameId: "Kunci", nameEn: "Lock", Icon: Lock },
  {
    key: "map-pinned",
    nameId: "Titik lokasi",
    nameEn: "Pinned location",
    Icon: MapPinned,
  },
  { key: "medal", nameId: "Medali", nameEn: "Medal", Icon: Medal },
  {
    key: "megaphone",
    nameId: "Pengumuman",
    nameEn: "Megaphone",
    Icon: Megaphone,
  },
  { key: "moon", nameId: "Bulan", nameEn: "Moon", Icon: Moon },
  {
    key: "package-check",
    nameId: "Paket siap",
    nameEn: "Ready package",
    Icon: PackageCheck,
  },
  {
    key: "palmtree",
    nameId: "Pohon palem",
    nameEn: "Palm tree",
    Icon: Palmtree,
  },
  {
    key: "party-popper",
    nameId: "Perayaan",
    nameEn: "Party Popper",
    Icon: PartyPopper,
  },
  { key: "pen-line", nameId: "Pena", nameEn: "Pen", Icon: PenLine },
  { key: "percent", nameId: "Persen", nameEn: "Percent", Icon: Percent },
  {
    key: "person-standing",
    nameId: "Orang berdiri",
    nameEn: "Standing person",
    Icon: PersonStanding,
  },
  {
    key: "piggy-bank",
    nameId: "Tabungan",
    nameEn: "Piggy Bank",
    Icon: PiggyBank,
  },
  { key: "pizza", nameId: "Pizza", nameEn: "Pizza", Icon: Pizza },
  { key: "popcorn", nameId: "Popcorn", nameEn: "Popcorn", Icon: Popcorn },
  {
    key: "presentation",
    nameId: "Presentasi",
    nameEn: "Presentation",
    Icon: Presentation,
  },
  { key: "printer", nameId: "Printer", nameEn: "Printer", Icon: Printer },
  {
    key: "projector",
    nameId: "Proyektor",
    nameEn: "Projector",
    Icon: Projector,
  },
  { key: "radio", nameId: "Radio", nameEn: "Radio", Icon: Radio },
  { key: "receipt", nameId: "Struk", nameEn: "Receipt", Icon: Receipt },
  { key: "recycle", nameId: "Daur ulang", nameEn: "Recycle", Icon: Recycle },
  {
    key: "refresh-ccw",
    nameId: "Segarkan",
    nameEn: "Refresh",
    Icon: RefreshCcw,
  },
  { key: "rocket", nameId: "Roket", nameEn: "Rocket", Icon: Rocket },
  { key: "route", nameId: "Rute", nameEn: "Route", Icon: Route },
  { key: "salad", nameId: "Salad", nameEn: "Salad", Icon: Salad },
  {
    key: "scan-face",
    nameId: "Pindai wajah",
    nameEn: "Face scan",
    Icon: ScanFace,
  },
  { key: "scissors", nameId: "Gunting", nameEn: "Scissors", Icon: Scissors },
  {
    key: "scroll-text",
    nameId: "Dokumen",
    nameEn: "Document",
    Icon: ScrollText,
  },
  { key: "send", nameId: "Kirim", nameEn: "Send", Icon: Send },
  { key: "settings", nameId: "Pengaturan", nameEn: "Settings", Icon: Settings },
  { key: "shield", nameId: "Perisai", nameEn: "Shield", Icon: Shield },
  {
    key: "shopping-cart",
    nameId: "Keranjang belanja",
    nameEn: "Shopping Cart",
    Icon: ShoppingCart,
  },
  { key: "signal", nameId: "Sinyal", nameEn: "Signal", Icon: Signal },
  { key: "siren", nameId: "Sirene", nameEn: "Siren", Icon: Siren },
  {
    key: "sliders-horizontal",
    nameId: "Pengaturan filter",
    nameEn: "Filters",
    Icon: SlidersHorizontal,
  },
  { key: "smile", nameId: "Senyum", nameEn: "Smile", Icon: Smile },
  { key: "sprout", nameId: "Tunas", nameEn: "Sprout", Icon: Sprout },
  {
    key: "square-check",
    nameId: "Kotak centang",
    nameEn: "Checkbox",
    Icon: SquareCheck,
  },
  {
    key: "stethoscope",
    nameId: "Stetoskop",
    nameEn: "Stethoscope",
    Icon: Stethoscope,
  },
  { key: "store", nameId: "Toko", nameEn: "Store", Icon: Store },
  { key: "sunset", nameId: "Senja", nameEn: "Sunset", Icon: Sunset },
  { key: "table", nameId: "Meja", nameEn: "Table", Icon: Table },
  { key: "tag", nameId: "Label", nameEn: "Tag", Icon: Tag },
  {
    key: "telescope",
    nameId: "Teleskop",
    nameEn: "Telescope",
    Icon: Telescope,
  },
  { key: "tent", nameId: "Tenda", nameEn: "Tent", Icon: Tent },
  { key: "theater", nameId: "Teater", nameEn: "Theater", Icon: Theater },
  { key: "thumbs-up", nameId: "Suka", nameEn: "Thumbs Up", Icon: ThumbsUp },
  { key: "timer", nameId: "Pengatur waktu", nameEn: "Timer", Icon: Timer },
  { key: "toilet", nameId: "Toilet", nameEn: "Toilet", Icon: Toilet },
  {
    key: "train-front",
    nameId: "Kereta",
    nameEn: "Train Front",
    Icon: TrainFront,
  },
  { key: "tram-front", nameId: "Trem", nameEn: "Tram Front", Icon: TramFront },
  {
    key: "tree-pine",
    nameId: "Pohon pinus",
    nameEn: "Pine tree",
    Icon: TreePine,
  },
  { key: "trophy", nameId: "Piala", nameEn: "Trophy", Icon: Trophy },
  {
    key: "user-check",
    nameId: "Pengguna terverifikasi",
    nameEn: "Verified user",
    Icon: UserCheck,
  },
  { key: "wallet", nameId: "Dompet", nameEn: "Wallet", Icon: Wallet },
  { key: "warehouse", nameId: "Gudang", nameEn: "Warehouse", Icon: Warehouse },
  { key: "wrench", nameId: "Perkakas", nameEn: "Wrench", Icon: Wrench },
];

export const masterIconByKey = Object.fromEntries(
  masterIcons.map(({ key, Icon }) => [key, Icon]),
) as Record<string, LucideIcon>;
